version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    groups:
      github-actions:
        patterns:
          - "*"

  # Rust/Cargo dependencies
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    groups:
      rust-cargo-dependencies:
        patterns:
          - "*"
