name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    env:
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-clippy
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test_redis:
    name: Test Suite(Redis Store)
    # env:
    #   REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    runs-on: blacksmith-4vcpu-ubuntu-2204
    services:
      redis:
        image: redis:latest
        #env:
        #  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli  ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: fetch  CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores
      - name: Log of cpu cores
        run: echo ${{ steps.cpu-cores.outputs.count }}
      - name: Cache Cargo
        uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache cargo-nextest
        id: cache-nextest
        uses: buildjet/cache@v3
        with:
          id: cache-nextest
          path: ~/.cargo/bin/cargo-nextest
          key: nextest-${{ runner.os }}-v0

      - name: Install cargo nextest
        if: steps.cache-nextest.outputs.cache-hit != 'true'
        uses: taiki-e/install-action@nextest
      - name: Run tests with RedisStore
        #env:
        #REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: cargo nextest run  --offline --config-file ./.config/nextest.toml --no-default-features --features redis-store
  fmt:
    name: Rustfmt
    env:
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    env:
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-clippy
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test_inmemory_store:
    name: Test Suite(InMemoryStore)
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache Cargo
        uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache cargo-nextest
        id: cache-nextest
        uses: buildjet/cache@v3
        with:
          id: cache-nextest
          path: ~/.cargo/bin/cargo-nextest
          key: nextest-${{ runner.os }}-v0

      - name: Install cargo nextest
        if: steps.cache-nextest.outputs.cache-hit != 'true'
        uses: taiki-e/install-action@nextest
      - name: Run tests
        #env:
        #REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: cargo nextest run  --offline --config-file ./.config/nextest.toml
