name: Benchmark pull requests

on: [pull_request]

concurrency:
  group: bench-${{ github.ref }}
  cancel-in-progress: true

jobs:
  runBenchmark:
    name: Run benchmark
    runs-on: blacksmith-4vcpu-ubuntu-2204
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: boa-dev/criterion-compare-action@v3
        with:
          # Disable the crate's default features for the benchmark.
          defaultFeatures: false
          # Branch to compare against.
          branchName: ${{ github.base_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
